---
output: github_document
---

```{r setup, include = FALSE}
# The README markdown generate by this rmd file, please edit the content within this R markdown.
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.path = "image/",
  fig.align = "center",
  echo = FALSE
)
```

# Note of Microsoft Azure AI Fundamentals (beta)

### Trophy 1: Get started with artificial intelligence on Azure

`AI01_azure_start` contains notes for Module 1: Get started with AI on Azure.

### Trophy 2: Create no-code predictive models with Azure Machine Learning

`AI02_NC_automated` contains notes for Module 2: Use automated machine learning in Azure Machine Learning.

`AI03_NC_regression` contains notes for Module 3: Create a Regression Model with Azure Machine Learning designer.

`AI04_NC_classification` contains notes for Module 4: Create a classification model with Azure Machine Learning designer.

`AI05_NC_clustering` contains notes for Module 5: Create a Clustering Model with Azure Machine Learning designer.

### Trophy 3: Explore computer vision in Microsoft Azure

`AI06_CV_analyze_image` contains notes for Module 6: Analyze images with the Computer Vision service.

`AI07_CV_classify_image` contains notes for Module 7: Classify images with the Custom Vision service.

`AI08_CV_detect_object` contains notes for Module 8: Detect objects in images with the Custom Vision service.

`AI09_CV_face_analysis` contains notes for Module 9: Detect and analyze faces with the Face service.

`AI10_CV_read_text` contains notes for Module 10: Read text with the Computer Vision service.

`AI11_CV_analyze_receipt` contains notes for Module 11: Analyze receipts with the Form Recognizer service.

### Trophy 4: Explore natural language processing

`AI12_NLP_analyze_text` contains notes for Module 12: Analyze text with the Text Analytics service.

`AI13_NLP_recognize_speech` contains notes for Module 13: Recognize and synthesize speech.

`AI14_NLP_translate_text` contains notes for Module 14: Translate text and speech.

`AI15_NLP_luis.` contains notes for Module 15: Create a language model with LUIS.

### Trophy 5: Explore conversational AI

`AI16_conversational_ai` contains notes for Module 16: Build a bot with QnA Maker and Azure Bot Service.


