---
output: github_document
---

```{r setup, include = FALSE}
# The README markdown generate by this rmd file, please edit the content within this R markdown.
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.path = "image/",
  fig.align = "center",
  echo = FALSE
)
```

# Note of Azure Data Scientist Associate

### Trophy 1: Take your first steps with Python

`DS01_Python_intro` contains notes for Module 1: What is Python?.

`DS02_Python_vs_code` contains notes for Module 2: Set up your Python beginner development environment with Visual Studio Code.

`DS03_Python_program` contains notes for Module 3: Create your first Python program.

`DS04_Python_branch_code` contains notes for Module 4: Branch code execution with the if...elif...else statement in Python. 

`DS05_Python_string` contains notes for Module 5: Manipulate and format string data for display in Python.

`DS06_Python_numeric` contains notes for Module 6: Perform mathematical operations on numeric data in Python.

`DS07_Python_library` contains notes for Module 7: Import standard library modules to add features to Python programs.

`DS08_Python_while` contains notes for Module 8: Iterate through code blocks by using the while statement.

### Trophy 2: Create machine learning models

### Trophy 3: Build AI solutions with Azure Machine Learning

### Code example

`Exercise` contains the python code for Exercise and Challenge of the three trophies.

Notes are referenced from Microsoft.